### PR TITLE
Prep for CPAN: Add MANIFEST and Makefile.PL

### PR DESCRIPTION
**Pull request by a3f**
The python runtime is available on pypi. Shouldn't the Perl runtime too be distributed over CPAN?

This patch adds the bare minimum required. `make dist` builds a distribution that can be uploaded via [PAUSE](https://pause.perl.org/).

### CODE REVIEW

**Comment by GreyCat** [comment]
It should be — we were actually preparing to do so — https://github.com/kaitai-io/kaitai_struct/issues/21 — but, unfortunately, the guy who pioneered Perl support disappeared from the project :(

I totally agree that it's a good idea to publish it (and, AFAIR, I even had some PAUSE account ages ago).

**Comment by GreyCat** [comment]
I've fixed some extra newlines near EOF + made Makefile.PL executable.

**Comment by a3f** [comment]
The Makefile.PL lacks a shebang (and it's usually run with `perl Makefile.PL` anyway). The line feed were left in for [reasons of portability](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

> but, unfortunately, the guy who pioneered Perl support disappeared from the project :(

Well, feel free to notify me if issues with the module here creep up. :)

**Comment by GreyCat** [comment]
Yeah, I've added the shebang, but forgot to push it.

> The line feed were left in for reasons of portability.

It's normal (and, actually, it's encouraged by lots of software like git) to have a single trailing EOL character at the end of file. However, the files you've submitted had not one, but two trailing EOL characters, thus making extra empty line. I'm certain that this is not needed in .gitignore, and I'm 99% sure that it's not needed in MANIFEST and Makefile.PL.

> Well, feel free to notify me if issues with the module here creep up. :)

If you're up to it, please take a look at current list of problems with Perl support in [our CI](http://kaitai.io/ci). Namely, there are:

* problem with array indexing expressions (as evidenced by ExprArray test)
* multiple problems with imports generation / testing
* problems with declaring/using parameterized types in Perl
* problems with custom process routines (ironically, the initial proposal for them — https://github.com/kaitai-io/kaitai_struct/issues/51 — was actually pioneered by Sergey Zelenyuk, our original Perl guy)

It's probably not that hard, but I'm not proficient enough in Perl to make good decisions in these...

**Comment by a3f** [comment]
> but two trailing EOL characters

Funny. I never noticed that Vim doesn't display that trailing new line. Thanks! ^^

> current list of problems with Perl support 

I will take a look when I have time. I will probably also add some author-only modules (`Dist::Zilla`) to aid with packaging/management.

**Pull request merged**
